### ISSUE TITLE
应用示例是否可以给一下？

### ISSUE THREAD

**Issue by xkungfu** [bytedo/gmf.core#2]
新手。
浏览器打开后，页面显示404.

**Http Status: 404
Controller [index] not found**

不知道下一步从哪开始。
是否可以给一个实际使用的示例，非常非常简单的就可以，谢谢！

添加了一个文件，显示:
文件内容：

```
var date=new Date();
console.log("程序已启动,启动时间："+date.getTime());
```

**Http Status: 500
Error: Controller [index] load error**

**Comment by yutent** [comment]
你用脚手架建立项目的话, 会有一个简单的demo的。

具体的文档, 我还在编写, 因为之前文档是放在gitee上的, 我注销那边的号之后, 忘了把文档弄回来了

**Comment by xkungfu** [comment]
好的，谢谢！

**Comment by yutent** [comment]
> 好的，谢谢！

文档在这里了
https://github.com/bytedo/gmf.core/wiki
